services:
  own-redis:
    container_name: upd-server
    image: "own-redis:v1.0"
    restart: always
    networks:
      - monitoring
    ports:
      - "8000:8000/udp"

networks:
  monitoring:
    driver: bridge
